Добавил обработку ошибки повтора
AlehaWP/YaPracticum pull request #8
Opened 2021-09-28 17:49 UTC by AlehaWP

2021-09-30 09:02 UTC, Perederey requested changes
1) Использовать context при работе с базой данных. Сейчас я вижу из методов, что он не используется. А это важно ;)
2) Использовать http.StatusXXX вместо 400,200 или переменных
3) Не вижу часть инкремента, который относиться к 8 уроку: хотел бы посмотреть на запросы ближе. Плюс к этому хочется подробнее увидеть работу с транзакциями, стейтментами и т.д. Можешь вернуть изменения, чтобы я их в этом PR увидел?
4) Используй pqx, вместо pq

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
> +		if err.Error() == "repeat" {
про ошибки разберем в 9 уроке - но сейчас ничего, пусть будет ;)

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
> +			w.Write([]byte(retURL))
кстати, можно несколькими способами сделать запись:

```go
_, err = io.WriteString(w,retURL)
    if err != nil {
    log.Panic(err)
    return
}
```

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
> +			w.WriteHeader(409)
лучше коды взять из констант http, они читабельнее - `http.StatusConflict` - только не совсем понимаю почему 409?

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
> +	aSuccessCode := 201
тоже это лишнее - используй `http.StatusCreated`

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
>  	userID := ctx.Value(global.CtxString("UserID")).(string)
а что если не найдет такой user? А если его в строку нельзя передавать?

И кстати для переменных в контексте лучше использовать свой тип
type UserKey string 

Не рекомендуется передавать simple типы в контекст.

2021-09-30 09:02 UTC, Perederey commented on internal/handlers/handlers_url.go
> +			aSuccessCode = 409
тут что-то немного намудрил? Не совсем понимаю почему опять 409?

2021-09-30 09:02 UTC, Perederey commented on internal/repository/db.go
> +		correlation_id VARCHAR(36),
что-то не вижу весь PR? хотелось бы и на функции создания посмотреть

2021-09-30 09:02 UTC, Perederey commented on internal/repository/db.go
> +	  ) VALUES ($1,$2,$3,$4,(SELECT COALESCE(id, 0) FROM users where user_enc_id=$5))`
немного заморочено, видимо тут какая-то логика вшита на уровне базы?

2021-09-30 09:02 UTC, Perederey commented on internal/repository/repository.go
> +	"github.com/lib/pq"
лучше pqx, чем pq

2021-10-01 17:04 UTC, AlehaWP commented on internal/repository/repository.go
> +	"github.com/lib/pq"
Хотелось делать через интерфейс sql

2021-10-01 17:06 UTC, AlehaWP commented on internal/repository/db.go
> +	  ) VALUES ($1,$2,$3,$4,(SELECT COALESCE(id, 0) FROM users where user_enc_id=$5))`
Да, просто привязываю ключ пользователя в БД. У нас так часто делают. Чтобы прописать связи по ключам

2021-10-01 17:06 UTC, AlehaWP commented on internal/repository/db.go
> +		correlation_id VARCHAR(36),
Потому что это изменения с 12го на 13

2021-10-01 17:06 UTC, AlehaWP commented on internal/handlers/handlers_url.go
> +			aSuccessCode = 409
По требованию инкремента 13

2021-10-01 17:08 UTC, AlehaWP commented on internal/handlers/handlers_url.go
>  	userID := ctx.Value(global.CtxString("UserID")).(string)
Свой тип сделал, что юзера не будет, по логике такого быть не должно. Он либо берется, либо формируется. Хотя конечно над обработкой ошибки формирования, подумаю

2021-10-01 17:08 UTC, AlehaWP commented on internal/handlers/handlers_url.go
> +	aSuccessCode := 201
Сделал

2021-10-01 17:08 UTC, AlehaWP commented on internal/handlers/handlers_url.go
> +			w.WriteHeader(409)
Сделал

2021-10-01 17:10 UTC, AlehaWP commented on internal/handlers/handlers_url.go
> +			w.Write([]byte(retURL))
Да, я видел такой. Спасибо. Потому что я его откинул, мне он показался не используемым в широких кругах. Теперь буду и его использовать

2021-10-02 08:36 UTC, Perederey approved these changes
Спасибо за правки!

Добавил два момента, которые пожалуйста исправь в следующем PR
1) Упрости работу с context, сейчас немного перемудрил (компилятор ругается на то, что ты скорее всего используешь поинтеры, а не обычный тип)
2) Немного добавь рефакторинг (убрав пакет Global) и сохраняй все в models

Но можно двигаться дальше

2021-10-02 08:36 UTC, Perederey commented on internal/global/global.go
> +func (u *UserKey) Get() string {
Getter и Setter обычно не используются в Go, принято напрямую обращаться, а зачем тебе из понтера получать строку.

Как вариант ты можешь сделать так (но это нет особого смысла)

```go
func (k UserKey) String() string {
    return k
}
```

Поэтому лучше убрать эту конструкцию

2021-10-02 08:36 UTC, Perederey commented on internal/global/global.go
> +	SaveURL(string, string, UserKey) (string, error)
передавать тут как раз UserKey не нужно, а просто обращаться к нему напрямую

2021-10-02 08:36 UTC, Perederey commented on internal/handlers/handlers_url.go
> +	userID := ctx.Value(global.CtxString("UserID")).(global.UserKey)
тут немного перемудрил, достаточно вот так

Для context важно не передавать string или еще какие-либо built-in типы.

```go
userID, ok := ctx.Value(global.UserKey).(string)
if !ok {
     w.WriteHeader(500)
     w.WriteHeader(http.StatusInternalServerError)
     return 
}
```

И лучше пакет Global (слишком общее название) переделать в models и там хранить все модели, ошибки там же можно и ключи для контекста.

file `errors.go`
```go
package models

var (
    ErrInvalidRequest = errors.New("invalid request)
)
```

file `context.go`
```go
package models

type CtxUserKey string
// ...

```

2021-10-06 21:07 UTC, merged