Inc14
AlehaWP/YaPracticum pull request #9
Opened 2021-10-16 23:54 UTC by AlehaWP

2021-10-18 08:34 UTC, Perederey requested changes
В целом хорошо!

Из основных ошибок
1) Надо разобраться с context.Context - сейчас он немного неправильно используется
2) Применить транзакции для удаления данных

2021-10-18 08:34 UTC, Perederey commented on cmd/shortener/main.go
> +	mainCtx, cancel := context.WithCancel(context.Background())
да можно просто ctx - main - избыточно

и после еще defer cancel() вызывать

2021-10-18 08:34 UTC, Perederey commented on internal/repository/db.go
> +	ctx, cancelfunc := context.WithTimeout(s.ctx, 30*time.Second)
ctx надо передавать в эту функцию, а не создавать его внутри.

2021-10-18 08:34 UTC, Perederey commented on internal/repository/db.go
> +	ctx, cancelFunc := context.WithTimeout(s.ctx, 20*time.Second)
и context не должен содержать в структуре, должен передавать в функцию

2021-10-18 08:34 UTC, Perederey commented on internal/repository/db.go
> +		ctx:     ctx,
отсюда надо убрать context

2021-10-18 08:34 UTC, Perederey commented on internal/repository/repository.go
> +var delCh chan delBufRow
я бы так не объявлял бы канал, лучше где-то в функции

2021-10-18 08:34 UTC, Perederey commented on internal/repository/repository.go
> +	cancel  context.CancelFunc
тоже самое про context и тут

2021-10-18 08:34 UTC, Perederey commented on internal/repository/db.go
> +	q := `DELETE FROM URLS WHERE for_delete=true`
надо еще применить транзакции для этого запроса, чтобы были rollback и commit.

2021-10-18 08:34 UTC, Perederey commented on internal/repository/repository.go
> +	timer := time.NewTimer(tP)
а вот таймер я бы создал в репозитории

2021-10-18 08:34 UTC, Perederey commented on internal/repository/repository.go
> +			s.ctx = context.Background()
не, не - так нельзя ;)

2021-10-18 08:34 UTC, Perederey commented on internal/repository/repository.go
> +			s.dBuf = append(s.dBuf, v)
лучше спрятать функцию setUrlsToDelFromBuf() внутри буфера. А в буфере есть только один метод s.Buffer.Add(v), тогда ты не будешь забывать ее вызывать вдругих местах.

Кроме этого функцию лучше назвать просто Flush()

2021-10-18 08:34 UTC, Perederey commented on internal/server/server.go
> +func (s *Server) Start(mCtx context.Context, repo models.Repository, opt models.Options) {
принято просто называть ctx context.Context

2021-10-18 21:44 UTC, KseyKseich commented on cmd/shortener/main.go
> +	mainCtx, cancel := context.WithCancel(context.Background())
Это легко ) Исправил

2021-10-18 21:46 UTC, KseyKseich commented on internal/repository/db.go
> +	ctx, cancelfunc := context.WithTimeout(s.ctx, 30*time.Second)
Сделал, но внутри тоже оставил. Именно здесь я добавляю отмену по  времени, если что-то пойдет не так. Или так не правильно? Надо передавать уровнем выше?

2021-10-18 21:46 UTC, KseyKseich commented on internal/repository/db.go
> +	ctx, cancelFunc := context.WithTimeout(s.ctx, 20*time.Second)
Исправил

2021-10-18 21:46 UTC, AlehaWP commented on internal/repository/db.go
> +		ctx:     ctx,
Исправил

2021-10-18 21:46 UTC, AlehaWP commented on internal/repository/repository.go
> +var delCh chan delBufRow
Сделал

2021-10-18 21:47 UTC, AlehaWP commented on internal/repository/db.go
> +	q := `DELETE FROM URLS WHERE for_delete=true`
Сделал

2021-10-18 21:47 UTC, KseyKseich commented on internal/repository/repository.go
> +	timer := time.NewTimer(tP)
Сделал

2021-10-18 21:50 UTC, AlehaWP commented on internal/repository/repository.go
> +			s.ctx = context.Background()
Убрал, это на самом деле избыточный функционал. Но для общего развития вопрос, если так нельзя, то  как в таких случаях делать какие-то действия? Прилетела отмена по контексту, мне надо выполнить что-то, но в обычной жизни для этого чего-то передается контекст, но передаваемый контекст уже закрыт. И чего делать?

2021-10-18 21:57 UTC, AlehaWP commented on internal/repository/repository.go
> +			s.dBuf = append(s.dBuf, v)
Не стал прятать методы именно в буфер, там используются поля структуры репозитория, а как обратиться к полям структуры в которую вложена структура буфера, не нашел. Передавать все в параметрах функции мне не понравилось. Возможно обсудим на 1 to 1

2021-10-18 21:59 UTC, KseyKseich commented on internal/server/server.go
> +func (s *Server) Start(mCtx context.Context, repo models.Repository, opt models.Options) {
Исправил

2021-10-19 17:21 UTC, Perederey commented on internal/repository/repository.go
> +			s.ctx = context.Background()
Фишка в том, что ты его передаешь в функци и делать такое не надо, подробнее расскажу на 1:1

2021-10-19 17:21 UTC, Perederey commented on internal/repository/repository.go
> +			s.dBuf = append(s.dBuf, v)
да, давай вынесем на 1:1

2021-10-19 17:22 UTC, Perederey approved these changes
Чтобы не тормозить процесс - сразу заапурвил исправления.

Контекст и каналы обсудим на 1:1

2021-10-19 18:04 UTC, merged